// Generated by https://quicktype.io

export interface GetLabelTypes {
  id: number;
  description: string;
  code: number;
  updatedAt: string;
  createdAt: string;
}

export interface GetWarehouses {
  id: number;
  description: string;
  code: string;
  labelA: boolean;
  labelB: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface GetMovTypes {
  id: number;
  description: string;
  code: number;
  updatedAt: string;
  createdAt: string;
  sortingOrder: number;
  labelA: boolean;
  labelB: boolean;
}
