// Generated by https://quicktype.io

export interface SubQueryResponse {
  PACKING: {
    labelA: number;
    labelB: number | null;
  };
  READY_TO_PICK: { labelA: number; labelB: number | null };
  RECEIVING: { labelA: number; labelB: number | null };
  SELLER_SHIPPED: { labelA: number; labelB: number | null };
  SENT: { labelA: number; labelB: number | null };
}
